//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionStrings
    {
        public int Id { get; set; }
        public string ServerAddress { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string DBName { get; set; }
    }
}
